FROM tomcat:9-jdk17

# Elimina apps por defecto (ROOT, etc.)
RUN rm -rf /usr/local/tomcat/webapps/*

# Copia tu .war generado como ROOT.war
COPY Phylix/dist/Phylix.war /usr/local/tomcat/webapps/ROOT.war

# Expone el puerto que usa Tomcat
EXPOSE 8080
